version: "3.0"
name: selvi_framework
services:
  web:
    container_name: selvi_framework_container
    image: mochrira/dev:1.0.0-apache
    volumes:
      - ../:/workspace
      - ./vhost.conf:/etc/apache2/conf.d/vhost.conf
    ports:
      - 8091:80